#!/bin/sh

DEFHOSTFILE=$HOME/.dompi-hostfile
HOSTFILE=$DEFHOSTFILE
RPROG=R
ORTERUN=orterun
USAGE='Usage: dompirun [option ...] [--] script [arg ...]

Options:

  -H    List of hosts on which to invoke processes.  This option takes
        precedence over the "-f" option.
  -R    Path of the R interpreter.  The default value is "R".
  -o    Path of the orterun command.
  -f    Path of the hostfile.  This option is ignored if the "-H" option
        is specified.  The default value is "'$DEFHOSTFILE'".
  -h    Print this message and exit.  All other options are ignored.'

# process the command line
while test "$1" != ""; do
    case "$1" in
        -H) if test "$2" = ""; then
                HOSTS=localhost
            else
                HOSTS=$2
            fi
            shift ;;
        -R) RPROG=$2; shift ;;
        -o) ORTERUN=$2; shift ;;
        -f) HOSTFILE=$2; shift ;;
        -h) echo "$USAGE" 1>&2; exit 1 ;;
        --) SCRIPT=$2; shift; shift; break ;;
        -*) echo "dompirun: unknown argument $1" 1>&2; exit 1 ;;
        *) SCRIPT=$1; shift; break
    esac
    shift
done

# sanity check the specified script file
if test "$SCRIPT" = ""; then
    echo "$USAGE" 1>&2; exit 1
else
    if test ! -f "$SCRIPT"; then
        echo "error: script file does not exist: $SCRIPT" 1>&2; exit 1
    fi
fi

# run the script
if test "$HOSTS" != ""; then
    exec "$ORTERUN" -H "$HOSTS" -n 1 "$RPROG" --vanilla --slave -f "$SCRIPT" --args "$@"
else
    if test -f $HOSTFILE; then
        exec "$ORTERUN" --hostfile "$HOSTFILE" -n 1 "$RPROG" --vanilla --slave -f "$SCRIPT" --args "$@"
    else
        echo "warning: hostfile $HOSTFILE not found" 1>&2
        exec "$ORTERUN" -n 1 "$RPROG" --vanilla --slave -f "$SCRIPT" --args "$@"
    fi
fi
